Repository MidwestAccessCoalition/lockbox_rails, pull requests merged in 2021-01, with the labels that each got.

#533 Update css for alert buttons (reconcile/confirm cash) on mobile
  app/assets/stylesheets/alert.scss
  app/views/lockbox_partners/_alerts.html.erb
Labels: ready for review

#521 Redact pii in app 467
  app/models/lockbox_action.rb
  app/models/note.rb
  app/models/support_request.rb
  app/workers/support_request_redaction_worker.rb
  db/migrate/20201129233712_add_closed_at_to_lockbox_actions.rb
  db/migrate/20201129234516_add_redacted_to_support_requests.rb
  db/migrate/20201206230927_add_may_contain_pii_to_notes.rb
  db/schema.rb
  lib/tasks/scheduled_tasks.rake
  lib/update_support_request.rb
  spec/lib/update_support_request_spec.rb
  spec/models/notes_spec.rb
  spec/models/support_request_spec.rb
  spec/workers/support_request_redaction_worker_spec.rb
Labels: migration, ready for review

#544 541 gas reinbursements
  app/javascript/src/transactions.js
  spec/system/support_request_creation_spec.rb
Labels: ready for review

#542 Make dashboard tables more responsive and fix support requests dashboard buttons
  app/views/admin_dashboard/index.html.erb
  app/views/lockbox_partners/users/index.html.erb
  app/views/support_requests/index.html.erb
Labels: ready for review

#557 Prevent paper_trail from recording name_or_alias
  app/models/support_request.rb
  spec/models/support_request_spec.rb
Labels: MVP, ready for review

#561 Fix - Adding menu items to hamburger nav when viewing a lockbox partner
  app/views/layouts/_nav_bar.html.erb
  spec/system/navbar_menu_spec.rb
Labels: ready for review

#540 Bump the ruby, rails, node versions
  .circleci/config.yml
  .nvmrc
  .ruby-version
  Gemfile
  Gemfile.lock
  README.md
  config/environments/production.rb
Labels: ready for review

#566 Added column for csv export
  app/models/support_request.rb
Labels: ready for review
